psql: &psql
  adapter: postgresql
  encoding: UTF8
  pool: 5
  host: localhost
  template: template0

development:
  <<: *psql
  database: brewbit_development
  username: brewbit
  password: brewbit

test:
  <<: *psql
  database: brewbit_test
  username: brewbit
  password: brewbit

staging:
  <<: *psql
  database: brewbit_production
  username: brewbit
  password: brewbit

production:
  <<: *psql
  database: brewbit_production
  username: brewbit
  password: brewbit
